---
services:
  phpipam-web:
    image: phpipam/phpipam-www:v1.7.3
    ports:
      - "8080:80"
    environment:
      - TZ=Europe/Berlin
      - IPAM_DATABASE_HOST=phpipam-mariadb
      # - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=/run/secrets/db_password
      - IPAM_DATABASE_WEBHOST=%
      - IPAM_DISABLE_INSTALLER=1 # do not add this line initially, see README.md
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    secrets:
      - db_password
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:v1.7.3
    environment:
      - TZ=Europe/Berlin
      - IPAM_DATABASE_HOST=phpipam-mariadb
      # - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=/run/secrets/db_password
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    secrets:
      - db_password
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:11.7.2
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      # - MYSQL_USER=phpipam
      # - MYSQL_PASSWORD=/run/secrets/db_password
    # command: >
    #  bash -c "
    #  export MYSQL_ROOT_PASSWORD=$(cat /run/secrets/db_root_password) &&
    #  exec docker-entrypoint.sh mariadbd
    #  "
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:

secrets:
  db_password:
    file: ./secrets/db_password
  db_root_password:
    file: ./secrets/db_root_password